mybatis:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.chan.dao

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode:true&characterEncoding:utf-8
    username: root
    password: 12345678

    #Druid配置
    druid:
      initial-size: 5                       #初始化连接:连接池启动时创建的初始化连接数量
      max-active: 50                        #连接池的最大数据库连接数。设为0表示无限制
      min-idle: 5                           #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,低于这个数量将创建新的连接
      max-wait: 10000                       #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
      pool-prepared-statements: false       #Oracle设置true，Mysql设为false
      remove_abandoned: true                #超过removeAbandonedTimeout时间后，是否进 行没用连接（废弃）的回收（默认为false，调整为true)
      remove_abandoned_timeout: 180         #超过时间限制，回收没有用(废弃)的连接（默认为 300秒，调整为180）
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
      filters: stat,wall

  #Freemarker配置
  freemarker:
      template-loader-path: classpath:/templates/
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl

  mvc:
    static-path-pattern : /static/**
  resources:
    static-locations: classpath:/static/

logging:
  level:
    root: INFO
    com:
      chan: INFO
    org:
      springframework:
        web:  DEBUG



Advertise:
  name: "阿牛"
